name: content-search-ai
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - numpy
  - matplotlib
  - pandas
  - tqdm
  - pillow            # παρέχει το module PIL
  - torchvision
  - pytorch
  - torchaudio
  - pycocotools
  - ipykernel
  - jupyterlab
  - faiss-cpu
  - ffmpeg
  - tk                # για tkinter/ttk (απαραίτητο σε conda)
  - pip:
      - ftfy
      - regex
      - opencv-python
      - pygame
      - git+https://github.com/openai/CLIP.git
      - deep-translator
      - openai-whisper
      - ttkbootstrap
