name: content-search-ai
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - numpy=1.26.4
  - matplotlib
  - pandas
  - tqdm
  - pillow
  - pytorch
  - torchvision
  - torchaudio
  - pycocotools
  - ipykernel
  - jupyterlab
  - faiss-cpu
  - ffmpeg
  - tk
  - pip:
      - ftfy
      - regex
      - opencv-python
      - pygame
      - git+https://github.com/openai/CLIP.git@dcba3cb2e2827b402d2701e7e1c7d9fed8a20ef1
      - deep-translator
      - openai-whisper
      - ttkbootstrap